(function() {
  window.langs = window.langs || {}
  window.langs.en = {
    summary: 'summary',
    profileDescription: `Senior JavaScript developer with over 8 years of experience in creating and scaling modern, robust web applications using Node.js, React, and frameworks like NestJS and Next.js. Skilled in designing and implementing resilient and scalable architectures, with expertise in performance optimization, process automation (linting, CI/CD), and API integration. Committed to innovation and building efficient solutions that reduce maintenance needs and drive product growth.`,
    experience: 'work experience',
    skills: 'skills',
    frontend: 'Frontend: ',
    backend: 'Backend: ',
    database: 'Database: ',
    devops: 'DevOps: ',
    tests: 'Tests: ',
    agile: 'Agile Methodologies: ',
    frontendValue: 'JavaScript, TypeScript, React, Vue.js, HTML5, CSS3, Sass, Webpack',
    backendValue: 'Node.js, Express, NestJS, GraphQL, RESTful APIs',
    databaseValue: 'MongoDB, PostgreSQL, MySQL, Redis',
    devopsValue: 'Docker, AWS (ECS), Linux',
    testsValue: 'Jest, Mocha, Chai, Supertest, Cypress',
    agileValue: 'Scrum, Kanban',

    education: 'education',
    course: 'Computer Science',
    college: 'University Anhembi Morumbi',
    courseFinished: '2016',

    email: 'Email: ',
    emailValue: 'diogo.domene@gmail.com',
    linkedin: 'Linkedin: ',
    linkedinValue: '/diogodomene',
    github: 'Github: ',
    githubValue: '/domenester',

    occupation: 'Full Stack Developer',
    age: '32 years old',
    contact: 'contact',
    phone: 'Phone: ',
    phoneNumber: '+55 (11) 99795-3111',
    address: 'Address: ',
    addressValue: 'São Paulo - Brazil',
    programming: 'Programming',
    modeling: 'Modeling',
    documentation: 'Documentation',
    architecture: 'Architecture',
    profile: 'Profile',
    lastJobDate: 'Since 2024/02',
    profileDescription: `Senior JavaScript developer with over 8 years of experience in creating and scaling modern, robust web applications using Node.js, React, and frameworks like NestJS and Next.js. Skilled in designing and implementing resilient and scalable architectures, with expertise in performance optimization, process automation (linting, CI/CD), and API integration. Committed to innovation and building efficient solutions that reduce maintenance needs and drive product growth.`,
    occupation8: 'Fullstack Developer / Solutions Architect',
    exp8_1: 'Worked on a platform for selling digital products integrated with a social network, featuring creator timelines, topic-based communities (forums), and an AI-powered chat interface.',
    exp8_2: 'Frontend: React + TailwindCSS + HeroUI (responsive – web/mobile), hosted on Vercel. Backend: Node.js with MongoDB, authentication via JWT.',
    exp8_3: 'Payments: Stripe API + Webhooks integration for marketplace transactions.',
    exp8_4: 'Cloud Architecture: Designed and implemented the entire infrastructure on AWS, using ECS + Fargate for container orchestration, S3 for file delivery, and AWS CodePipeline for CI/CD (integrated with GitHub and GitLab).',
    exp8_5: 'Monitoring & Observability: CloudWatch for logs and metrics, with Prometheus, Grafana, and Glitchtip via Easypanel.',
    exp8_6: 'Tech Leadership: Conduct code reviews, approve/reject merge requests, and guide the team on best practices to ensure code maintainability and scalability.',
    exp8_7: 'AI Integration: Implemented AI agents to enhance both end-user interaction and development productivity.',
    occupation7: 'Senior Full Stack',
    exp7_1: 'Designed and implemented new features in a JS-based stack with Node.js, GraphQL, SQL, and NestJS for backend microservices, and React/Next.js on the frontend.',
    exp7_2: 'Key contributor to the financial system, bridging legacy systems with new data handling structures. Developed complex business rules connecting clients, employees, and healthcare providers, central to the company\'s operations.',
    occupation6: 'Senior Full Stack',
    exp6_1: 'Developed a checklist platform with a microservices architecture, employing Seneca for inter-service communication in Node.js, PostgreSQL for data persistence, and Redis for caching.',
    exp6_2: "Utilized Rancher for container orchestration to enhance backend availability. On the frontend, implemented real-time checklist updates using Angular 8's Observable pattern.",
    occupation5: 'Middle Full Stack',
    exp5_1: "Contributed to the EPICALL project, a comprehensive communication platform supporting SIP telephony, real-time chat, conference scheduling, and custom telephony features. Tech stack included Node.js on the backend and Angular 6/React on the frontend.",
    occupation4: 'Junior Back-end Developer',
    exp4_1: "Developed a cryptocurrency exchange leveraging BlockIO API for blockchain-based transactions, with Node.js and Firebase to support real-time operations.",
    exp4_2: "Chose Loopback 3 for REST service exposure, optimizing productivity in a high-speed development environment.",
    occupation3: 'Junior Back-End Developer',
    exp3_1: "Contributed to a backend for Santander Bank, improving availability and performance issues with a TypeScript-based Node.js architecture.",
    exp3_2: "Leveraged Docker and Kubernetes for scalable deployment, and used Redis for high-speed data caching, ensuring optimal performance. Comprehensive unit tests were implemented using Mocha and Chai.",
    occupation2: 'Sharepoint Developer',
    occupation1: 'Web Developer',
    techs: 'Technology',
    languages: 'languages',
    english: 'English',
    advanced: 'Advanced',
    native: 'Native',
    portuguese: 'Portuguese'
  }
})()