(function() {
  window.langs = window.langs || {}
  window.langs.pt = {
    summary: 'resumo',
    experience: 'experiência profissional',
    skills: 'habilidades',
    frontend: 'Frontend: ',
    backend: 'Backend: ',
    database: 'Banco de dados: ',
    devops: 'DevOps: ',
    tests: 'Testes: ',
    agile: 'Metodologias Ágeis: ',
    frontendValue: 'JavaScript, TypeScript, React, Vue.js, HTML5, CSS3, Sass, Webpack',
    backendValue: 'Node.js, Express, NestJS, GraphQL, RESTful APIs',
    databaseValue: 'MongoDB, PostgreSQL, MySQL, Redis',
    devopsValue: 'Docker, AWS (ECS), Linux',
    testsValue: 'Jest, Mocha, Chai, Supertest, Cypress',
    agileValue: 'Scrum, Kanban',

    education: 'educação',
    course: 'Ciência da Computação',
    college: 'Universidade Anhembi Morumbi',
    courseFinished: '2016',

    email: 'Email: ',
    emailValue: 'diogodomene@gmail.com',
    linkedin: 'Linkedin: ',
    linkedinValue: '/diogodomene',
    github: 'Github: ',
    githubValue: '/domenester',




    occupation: 'Desenvolvedor Full Stack',
    age: '32 anos',
    contact: 'contato',
    phone: 'Telefone: ',
    phoneNumber: '+55 (11) 99795-3111',
    address: 'Endereço: ',
    addressValue: 'São Paulo - Brasil',
    programming: 'Programação',
    modeling: 'Modelagem',
    documentation: 'Documentação',
    architecture: 'Arquitetura',
    profile: 'Perfil',
    lastJobDate: 'Desde 2024/02',
    profileDescription: `Desenvolvedor JavaScript sênior com mais de 8 anos de experiência em criar e escalar aplicações web modernas e robustas, utilizando Node.js, React, e frameworks como NestJS e Next.js. Hábil em projetar e implementar arquiteturas resilientes e escaláveis, com expertise na otimização de performance, automação de processos (linting, CI/CD) e integração de APIs. Comprometido com a inovação e a criação de soluções eficientes que reduzem a necessidade de manutenção e impulsionam o crescimento do produto.`,
    experience: 'experiência',
    occupation8: 'Desenvolvedor Fullstack / Arquiteto de Soluções',
    exp8_1: 'Trabalhei em uma plataforma para venda de produtos digitais integrada a uma rede social, com recursos de linha do tempo para criadores, comunidades baseadas em tópicos (fóruns) e interface de chat com IA.',
    exp8_2: 'Frontend: React + TailwindCSS + HeroUI (responsivo – web/mobile), hospedado na Vercel. Backend: Node.js com MongoDB, autenticação via JWT.',
    exp8_3: 'Pagamentos: Integração com API Stripe + Webhooks para transações de marketplace.',
    exp8_4: 'Arquitetura em Nuvem: Projetei e implementei toda a infraestrutura na AWS, usando ECS + Fargate para orquestração de contêineres, S3 para entrega de arquivos e AWS CodePipeline para CI/CD (integrado com GitHub e GitLab).',
    exp8_5: 'Monitoramento e Observabilidade: CloudWatch para logs e métricas, com Prometheus, Grafana e Glitchtip via Easypanel.',
    exp8_6: 'Liderança Técnica: Realizo revisões de código, aprovo/rejeito solicitações de merge e oriento a equipe sobre melhores práticas para garantir a manutenção e escalabilidade do código.',
    exp8_7: 'Integração de IA: Implementei agentes de IA para aprimorar tanto a interação do usuário final quanto a produtividade no desenvolvimento.',
    occupation7: 'Engenheiro de Software Sênior',
    exp7_1: "Criei e implementei novas funcionalidades em uma stack baseada em JavaScript, com Node.js, GraphQL, SQL e NestJS para serviços no backend, e React/Next.js no frontend.",
    exp7_2: "Contribuí para o desenvolvimento do sistema financeiro, integrando sistemas legados com novas estruturas de manipulação de dados. Desenvolvi regras de negócio complexas que conectavam clientes, funcionários e prestadores de serviços de saúde, essenciais para as operações da empresa.",
    occupation6: 'Engenheiro de Software',
    exp6_1: "Desenvolvi uma plataforma de checklist com arquitetura de microsserviços, utilizando Seneca para comunicação entre serviços em Node.js, PostgreSQL para persistência de dados e Redis como cache.",
    exp6_2: "Utilizei Rancher para orquestração de containers, aumentando a disponibilidade do backend. No frontend, implementei atualizações em tempo real nos checklists usando o padrão Observable do Angular 8.",
    occupation5: 'Engenheiro de Software',
    exp5_1: "Contribuí para o projeto EPICALL, uma plataforma de comunicação completa com suporte a telefonia SIP, chat em tempo real, agendamento de conferências e funcionalidades personalizadas de telefonia. O stack incluía Node.js no backend e Angular 6/React no frontend.",
    occupation4: 'Engenheiro de Software',
    exp4_1: "Desenvolvi uma exchange de criptomoedas utilizando a API BlockIO para transações baseadas em blockchain, com Node.js e Firebase para suportar operações em tempo real.",
    exp4_2: "Escolhi o Loopback 3 para exposição de serviços REST, otimizando a produtividade em um ambiente de desenvolvimento ágil.",
    occupation3: 'Desenvolvedor Back-End',
    exp3_1: "Contribuí para o desenvolvimento de um backend para o Banco Santander, melhorando problemas de disponibilidade e performance com uma arquitetura Node.js baseada em TypeScript.",
    exp3_2: "Utilizei Docker e Kubernetes para deployment escalável, e Redis para cache de dados, garantindo desempenho otimizado. Implementei testes unitários com Mocha e Chai.",
    occupation2: 'Consultor Sharepoint',
    occupation1: 'Desenvolvedor Web',
    education: 'formação',
    course: 'Ciência da Computação',
    college: 'Universidade Anhembi Morumbi',
    courseFinished: '2016',
    techs: 'Tecnologias',
    languages: 'idiomas',
    english: 'Inglês',
    advanced: 'Avançado',
    native: 'Nativo',
    portuguese: 'Português'
  }
})()